### ISSUE TITLE
compileNGScript - Object has no method 'existsSync'

### ISSUE THREAD

**Issue by fromthemills** [pbastowski/angular-meteor-babel#25]
Hi, 

just tried upgrading my project to the latest beta version of meteor (1.3.3-beta.1) to get a bug fixed. I got the following error in your package.

```
=> Errors prevented startup:  
   While loading plugin `compileNGScript` from package `pbastowski:angular-babel`:
   packages/compileNGScript_plugin.js:164:12: Object [object Object] has no method 'existsSync'
   at getCustomConfig (packages/compileNGScript_plugin.js:164:12)
   at Package (packages/compileNGScript_plugin.js:37:20)
   at packages/compileNGScript_plugin.js:179:4
   at packages/compileNGScript_plugin.js:186:3
```

Is this some breaking change they overlooked in the beta or might this be related to your package?
I hope the error gives you enough info. Let me know if you need more detailed information about my setup.

**Comment by pbastowski** [comment]
I have just pushed 1.3.5. Please try it and let me know if it helps.

**Comment by Ben305** [comment]
I was running into the same problem, 1.3.5 seems to fixes that. Can you remove the console.log statement again?

**Comment by fromthemills** [comment]
Yup, I can confirm this is fixed in version 1.3.6. Thanks for the quick response!

**Comment by pbastowski** [comment]
@Ben305 
Done and thanks for catching that.

**Comment by iain17** [comment]
I've just tried updating to Meteor 1.3.4.1 and still have this issue?

**Comment by Ben305** [comment]
@iain17 Are you sure that you are using the latest version? Updating the Meteor Release doesn't mean that the used package version is updated, too.

**Comment by iain17** [comment]
@Ben305 I made sure to update every package before doing the meteor update. Has the atmosphere package been updated?

**Comment by pbastowski** [comment]
@iain17 If you are asking if `pbastowski:angular-babel` has been upgraded to work with Meteor 1.3 then the answer is yes. I use it myself even with Meteor 1.4-beta.2.

If you share a link to your repo then I could have a look at it for you.

**Comment by ppss198** [comment]
I've just tried updating to Meteor 1.3.4.1 and still have this issue.........

xmapp 1.4: updated to Meteor 1.3.4.1.

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While loading plugin `compileNGScript` from package `pbastowski:angular-babel`:
   <runJavaScript-48>:155:12: Object [object Object] has no method 'existsSync'
   at getCustomConfig (<runJavaScript-48>:155:12)
   at Package (<runJavaScript-48>:37:20)
   at <runJavaScript-48>:170:4
   at <runJavaScript-48>:177:3

**Comment by pbastowski** [comment]
@ppss198 
The latest version is 1.3.6. Try this

```
meteor update pbastowski:angular-babel
```

If you still get the error then please post the contents of your `.meteor/versions` file and `.meteor/packages` file, so I can see what version of the package Meteor is working with.

**Comment by ppss198** [comment]
it's right, the problem is solved,thank you very much

**Comment by hansonchun** [comment]
Hi,

I just updated to Meteor 1.3.4.1 as well and started getting this issue. I'm currently on angular-babel 1.3.6.

> Started MongoDB.
> Errors prevented startup:
> 
> While processing files with pbastowski:angular-babel (for target web.browser):
> packages/compileNGScript/plugin/ng-script-compiler.js:107:1: error: couldn't process source due to parse error: 
> Unexpected character '#' (1:0)
>   at processFile (packages/compileNGScript/plugin/ng-script-compiler.js:107:1)
>   at Array.forEach (native)
>   at Object.processFiles (packages/compileNGScript/plugin/ng-script-compiler.js:39:1)
> 
> While processing files with angular-templates (for target web.browser):
> test/android/project/build/intermediates/assets/debug/www/application/index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
> test/android/project/assets/www/application/index.html:1: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
> 
> While processing files with pbastowski:angular-babel (for target os.windows.x86_32):
> packages/compileNGScript/plugin/ng-script-compiler.js:107:1: error: couldn't process source due to parse error: 
> 
> Unexpected character '#' (1:0)
>   at processFile (packages/compileNGScript/plugin/ng-script-compiler.js:107:1)
>   at Array.forEach (native)
>   at Object.processFiles (packages/compileNGScript/plugin/ng-script-compiler.js:39:1)

**Comment by pbastowski** [comment]
@hansonchun 

I don't have a Windows machine at this moment, so, it's not possible for me to replicate your issue.
Having said that, try doing this:
1. Stop your meteor app
2. Delete the `./meteor/local` directory, which is where Meteor caches all it's compiled code
3. Start your meteor app again

If you keep seeing the same problem then please post a link to your repo and I will have a look at it for you.

Please note that I will be away on vacation for the next 10 days, so, I may not be able to respond to your query quickly.

**Comment by hansonchun** [comment]
Yes, that seemed to fix it. Thanks so much!

**Comment by tmgriffith** [comment]
@pbastowski 

Not sure what I did wrong, Was only trying to add the dependency

`meteor add pbastowski:angular-babel
C:\Users\Tim\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: No metadata files found for isopack at: /C/Users/Tim/AppData/Local/.meteor/packages/pbastowski_angular-babel/1.3.6
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
    at C:\tools\packaging\tropohouse.js:514:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Tim\AppData\Local\.meteor\packages\meteor-tool\1.4.0\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:513:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:448:20)
    at C:\tools\packaging\tropohouse.js:592:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:589:20)
    at C:\tools\project-context.js:748:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:747:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._downloadMissingPackages (C:\tools\project-context.js:746:13)
    at C:\tools\project-context.js:268:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:258:18)
    at C:\tools\project-context.js:250:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:249:13)
    at C:\tools\cli\commands-packages.js:1976:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Command.func (C:\tools\cli\commands-packages.js:1975:27)
    at C:\tools\cli\main.js:1402:23`

**Comment by kvasilaky** [comment]
Hi:
I am following this tutorial to create a forum with meteor. I am 1 hour new to meteor and trying to get this up an running quickly:
https://www.codementor.io/meteor/tutorial/build-forum-engine-using-meteor-angularjs

I updated my meteor version (meteor update pbastowski:angular-babel). 
I'm having trouble running the app at the point where it says: "At this point you can run the app."

The error I get is " While processing files with angular-templates (for target web.browser):
   native: main.html has wrong layout"

main.html (below) is in client/main.html, along with main.js, which calls it. Can anyone suggest any fixes?

Thank you!!!
KV

<head>
  <title>forum</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
  {{> info}}
</body>

<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>

<template name="info">
  <h2>Learn Meteor!</h2>
  <ul>
    <li><a href="https://www.meteor.com/try" target="_blank">Do the Tutorial</a></li>
    <li><a href="http://guide.meteor.com" target="_blank">Follow the Guide</a></li>
    <li><a href="https://docs.meteor.com" target="_blank">Read the Docs</a></li>
    <li><a href="https://forums.meteor.com" target="_blank">Discussions</a></li>
  </ul>
</template>

**Comment by pbastowski** [comment]
Hi @kathrynthegreat 
The problem appears to be reported by the `angular-templates` package, as it states in the error message you supplied, and not `pbastowski:angular-babel`. 

Most likely, if you have removed `blaze-html-templates` and added `angular-templates`, the issue is to do with some extra code in your `main.html`, such as 

``` html
<template ...>
....
</template>
```

I had a look at the tutorial link you posted above, but I don't see any `main.html` in it. There is an `index.html` there, however???

To update meteor itself type in `meteor update` without any further package names. Otherwise only the package you specified will be updated.

If you provide a link to your repo on github then I can have a quick look and help you a bit more.
